services:
  keycloak-mysql:
    image: mysql:8
    container_name: keycloak-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
#    ports:
#      - "3306:3306"
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        DB_VENDOR: MYSQL
        DB_ADDR: keycloak-mysql
        DB_DATABASE: keycloak
        DB_USER: KEYCLOAK
        DB_PASSWORD: PASSWORD
    ports:
        - "8181:8080"
    depends_on:
        - keycloak-mysql
    volumes:
        - ./docker/keycloak/realm/:/opt/keycloak/data/import

